use practice_snowflake;


create or replace table result(
ACCOUNT_ID VARCHAR(100000),
GA_DATE VARCHAR(100000),
GA_INTERNALPROMOTIONCREATIVE VARCHAR(100000),
GA_DIMENSION19 VARCHAR(100000),
GA_DEVICECATEGORY VARCHAR(100000),
GA_CHANNELGROUPING VARCHAR(100000),
GA_INTERNALPROMOTIONCLICKS VARCHAR(100000),
GA_INTERNALPROMOTIONVIEWS VARCHAR(100000),
GA_SESSIONS VARCHAR(100000),
GA_SESSIONDURATION VARCHAR(100000),
GA_INTERNALPROMOTIONCTR VARCHAR(100000),
GA_MARKET VARCHAR(100000)
);


CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
TYPE=CSV
FIELD_DELIMITER=',' SKIP_HEADER=1
NULL_IF=('NULL','null')
EMPTY_FIELD_AS_NULL=true;

CREATE OR REPLACE STAGE MY_STAGE
url='s3://{bucket-name}/sample.csv'
credentials=(aws_key_id='<access-key>' aws_secret_key='<secret-access-key')
file_format=my_csv_format;

show stages;

LIST @PRACTICE_SNOWFLAKE.PUBLIC.MY_STAGE;

COPY INTO RESULT 
FROM @PRACTICE_SNOWFLAKE.PUBLIC.MY_STAGE
FILE_FORMAT=(FORMAT_NAME=MY_CSV_FORMAT);

truncate table result;

SELECT * FROM "PRACTICE_SNOWFLAKE"."PUBLIC"."RESULT" limit 5;
